# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170426_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default/Path.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
