# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='\u6807\u9898')),
                ('link', models.URLField(verbose_name='\u94fe\u63a5')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_article', to='account.Profile')),
                ('collection_user', models.ManyToManyField(blank=True, related_name='collection_articles', to='account.Profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='article_liked', to='account.Profile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='account.Subject')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
